url: "https://elineasmit.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Dr. Eline A. Smit" # the name of your site, e.g. ACME Corp.
description: "University of Konstanz"
