url: "https://elineasmit.github.io/elineasmit/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/academic" # the subpath of your site, e.g. /blog
title: "Dr. Eline A. Smit" # the name of your site, e.g. ACME Corp.
description: "University of Konstanz"
