menu:
- {name: 'about', url: '/about'}
- {name: 'publications', url: '/publications'}
- {name: 'media', url: '/media'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

about:
- {name: 'About me', title: 'Postdoctoral Researcher', department: 'Department of Linguistics', institution: 'University of Konstanz', email: 'eline.smit@uni-konstanz.de', image: 'assets/img/elinesmit.jpg'}

media:
- {name: 'Interview', url: 'vector-calculus'}
- {name: 'Podcast', url: 'quantum-mechanics'}
- {name: 'Radio', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/elineasmit'}
- {icon: 'twitter', link: 'https://twitter.com/elineadrianne'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/dr-eline-a-smit-80a21263/'}

contacts:
- {name: 'Dr. Eline A. Smit', title: 'Postdoctoral Research Fellow', department: 'Deparment of Linguistics', institution: 'University of Konstanz', institution_address: 'Universitätsstraße 10, 78464 Konstanz, Germany', email: 'eline.smit@uni-konstanz.de', image: 'assets/img/contact.jpg'}
