menu:
- {name: 'about', url: '/about'}
- {name: 'publications', url: '/publications'}
- {name: 'media', url: '/media'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

about:
- {name: 'About me', title: 'Data analist', institution: 'Netherlands Court of Audit', email: 'e.smit@rekenkamer.nl', image: 'assets/img/contact.jpg'}

media:
- {name: 'Interview', url: 'vector-calculus'}
- {name: 'Podcast', url: 'quantum-mechanics'}
- {name: 'Radio', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/elineasmit'}
- {icon: 'twitter', link: 'https://twitter.com/elineadrianne'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/dr-eline-a-smit-80a21263/'}

contacts:
- {name: 'Dr. Eline A. Smit', title: 'Data analist', institution: 'Netherlands Court of Audit', institution_address: 'The Hague', email: 'e.smit@rekenkamer.nl', image: 'assets/img/pianoeline.jpg'}
